import type { Config } from 'tailwindcss';

export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        lavender: {
          50: '#F5F3FF',
          100: '#EDE9FE',
          200: '#DDD6FE',
          300: '#C4B5FD',
          400: '#A78BFA',
          500: '#8B5CF6',
          600: '#7C3AED',
          700: '#6D28D9',
          800: '#5B21B6',
          900: '#4C1D95',
        },
        paper: {
          50: '#F8F7FF',
          100: '#F0EFFA',
          200: '#E5E3F6',
        },
        ink: {
          DEFAULT: '#1F2937',
          light: '#4B5563',
          muted: '#9CA3AF',
        },
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            '--tw-prose-body': 'rgb(75 85 99)',
            '--tw-prose-headings': 'rgb(31 41 55)',
            '--tw-prose-links': 'rgb(139 92 246)',
            '--tw-prose-bold': 'rgb(31 41 55)',
            '--tw-prose-counters': 'rgb(156 163 175)',
            '--tw-prose-bullets': 'rgb(156 163 175)',
            '--tw-prose-hr': 'rgb(229 231 235)',
            '--tw-prose-quotes': 'rgb(75 85 99)',
            '--tw-prose-quote-borders': 'rgb(139 92 246)',
            '--tw-prose-captions': 'rgb(107 114 128)',
            '--tw-prose-code': 'rgb(139 92 246)',
            '--tw-prose-pre-code': 'rgb(229 231 235)',
            '--tw-prose-pre-bg': 'rgb(30 41 59)',
            '--tw-prose-th-borders': 'rgb(229 231 235)',
            '--tw-prose-td-borders': 'rgb(229 231 235)',
            hr: {
              borderColor: 'rgb(229 231 235)',
              marginTop: '2.5em',
              marginBottom: '2.5em',
            },
            h1: {
              fontWeight: '800',
              fontSize: '2em',
              marginTop: '0',
              marginBottom: '1.25em',
              lineHeight: '1.3',
              letterSpacing: '-0.025em',
            },
            h2: {
              fontWeight: '700',
              fontSize: '1.5em',
              marginTop: '2.5em',
              marginBottom: '1em',
              lineHeight: '1.4',
              paddingBottom: '0.5em',
              borderBottomWidth: '2px',
              borderBottomColor: 'rgb(229 231 235)',
              letterSpacing: '-0.02em',
            },
            h3: {
              fontWeight: '600',
              fontSize: '1.25em',
              marginTop: '2em',
              marginBottom: '0.75em',
              lineHeight: '1.5',
            },
            'h4,h5,h6': {
              fontWeight: '600',
              marginTop: '1.5em',
              marginBottom: '0.5em',
              lineHeight: '1.5',
            },
            p: {
              marginTop: '0',
              marginBottom: '1.5em',
              lineHeight: '1.8',
            },
            a: {
              color: 'rgb(139 92 246)',
              textDecoration: 'none',
              fontWeight: '500',
              borderBottomWidth: '1px',
              borderBottomColor: 'transparent',
              '&:hover': {
                color: 'rgb(124 58 237)',
                borderBottomColor: 'rgb(124 58 237)',
              },
            },
            blockquote: {
              fontWeight: '500',
              fontStyle: 'italic',
              color: 'rgb(75 85 99)',
              borderLeftWidth: '4px',
              borderLeftColor: 'rgb(139 92 246)',
              paddingLeft: '1.5em',
              backgroundColor: 'rgb(245 243 255)',
              borderRadius: '0 0.5rem 0.5rem 0',
            },
            code: {
              color: 'rgb(139 92 246)',
              fontWeight: '600',
              fontSize: '0.875em',
              backgroundColor: 'rgb(245 243 255)',
              padding: '0.2rem 0.5rem',
              borderRadius: '0.375rem',
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              color: 'rgb(229 231 235)',
              backgroundColor: 'rgb(30 41 59)',
              overflowX: 'auto',
              borderRadius: '0.75rem',
              padding: '1.25rem',
              border: '1px solid rgb(229 231 235)',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            },
            'pre code': {
              backgroundColor: 'transparent',
              borderWidth: '0',
              borderRadius: '0',
              padding: '0',
              fontWeight: '400',
              color: 'inherit',
              fontSize: '0.875rem',
              fontFamily: 'ui-monospace, SFMono-Regular, monospace',
              lineHeight: '1.7',
            },
            'pre code::before': {
              content: '""',
            },
            'pre code::after': {
              content: '""',
            },
            table: {
              width: '100%',
              tableLayout: 'auto',
              textAlign: 'left',
              marginTop: '1.5em',
              marginBottom: '1.5em',
              fontSize: '0.875em',
              lineHeight: '1.7',
              borderRadius: '0.5rem',
              overflow: 'hidden',
            },
            thead: {
              color: 'rgb(17 24 39)',
              fontWeight: '600',
              borderBottomWidth: '2px',
              borderBottomColor: 'rgb(229 231 235)',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
              fontSize: '0.875rem',
            },
            'thead th': {
              verticalAlign: 'bottom',
              paddingRight: '1rem',
              paddingBottom: '0.875rem',
              paddingLeft: '1rem',
            },
            'tbody tr': {
              borderBottomWidth: '1px',
              borderBottomColor: 'rgb(229 231 235)',
            },
            'tbody tr:last-child': {
              borderBottomWidth: '0',
            },
            'tbody tr:nth-child(even)': {
              backgroundColor: 'rgb(249 250 251)',
            },
            'tbody td': {
              verticalAlign: 'top',
              paddingTop: '0.875rem',
              paddingRight: '1rem',
              paddingBottom: '0.875rem',
              paddingLeft: '1rem',
            },
            img: {
              borderRadius: '0.75rem',
              boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
            },
          },
        },
        dark: {
          css: {
            '--tw-prose-body': 'rgb(209 213 219)',
            '--tw-prose-headings': 'rgb(243 244 246)',
            '--tw-prose-links': 'rgb(167 139 250)',
            '--tw-prose-bold': 'rgb(243 244 246)',
            '--tw-prose-counters': 'rgb(156 163 175)',
            '--tw-prose-bullets': 'rgb(75 85 99)',
            '--tw-prose-hr': 'rgb(55 65 81)',
            '--tw-prose-quotes': 'rgb(156 163 175)',
            '--tw-prose-quote-borders': 'rgb(167 139 250)',
            '--tw-prose-captions': 'rgb(156 163 175)',
            '--tw-prose-code': 'rgb(167 139 250)',
            '--tw-prose-pre-code': 'rgb(229 231 235)',
            '--tw-prose-pre-bg': 'rgb(30 41 59)',
            '--tw-prose-th-borders': 'rgb(55 65 81)',
            '--tw-prose-td-borders': 'rgb(55 65 81)',
            hr: {
              borderColor: 'rgb(55 65 81)',
            },
            h1: {
              color: 'rgb(243 244 246)',
            },
            h2: {
              color: 'rgb(243 244 246)',
              borderBottomColor: 'rgb(55 65 81)',
            },
            h3: {
              color: 'rgb(243 244 246)',
            },
            'h4,h5,h6': {
              color: 'rgb(243 244 246)',
            },
            a: {
              color: 'rgb(167 139 250)',
              '&:hover': {
                color: 'rgb(196 181 253)',
                borderBottomColor: 'rgb(196 181 253)',
              },
            },
            blockquote: {
              color: 'rgb(156 163 175)',
              borderLeftColor: 'rgb(167 139 250)',
              backgroundColor: 'rgb(30 30 46)',
            },
            code: {
              backgroundColor: 'rgb(30 30 46)',
              color: 'rgb(167 139 250)',
            },
            pre: {
              backgroundColor: 'rgb(30 41 59)',
              borderColor: 'rgb(55 65 81)',
            },
            thead: {
              color: 'rgb(243 244 246)',
              borderBottomColor: 'rgb(55 65 81)',
            },
            'tbody tr': {
              borderBottomColor: 'rgb(55 65 81)',
            },
            'tbody tr:nth-child(even)': {
              backgroundColor: 'rgb(30 30 46)',
            },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
  ],
} satisfies Config;